---
inventory:
  plugin: SimpleInventory
  options:
    host_file: inventory/hosts.yaml
    group_file: inventory/groups.yaml
   
routers:
  hostname: router.example.com
  username: admin
  password: secret
  platform: cisco_ios



# logging:
#   level: DEBUG
#   file: nornir.log

# ssh:
#   extras:
#     timeout: 10
#   config_file: ssh_config

# netmiko:
#   extras:
#     global_delay_factor: 2
#     timeout: 10
#   platform: huawei_hua

